---
title: "Tract to CCA"
output: html_document
date: "2023-02-10"
---

```{r}
devtools::install_github("CMAP-REPOS/cmapgeo")
library(cmapgeo)
install.packages("dplyr")
library(dplyr)
install.packages("tidyverse")
library(tidyverse)
install.packages("tidycensus")
library(tidycensus)
```
# View the block groups with housing units split between multiple CCAs
```{r}
tract_sf
cca_sf
filter(xwalk_tract2cca, hu_pct < 1)
```
# Estimate CCA-level housing vacancy rates from block group-level Census data
```{r}
xwalk_tract2cca
df_tract <- tidycensus::get_decennial(
  geography = "tract", variables = c("H1_001N", "H1_003N"),
  year = 2020, state = "IL", county = c("031", "043"), output = "wide"
) %>%
  suppressMessages() %>%  
  select(geoid_tract = GEOID, hu_tot = H1_001N, hu_vac = H1_003N)

```
```{r}
df_tract <- xwalk_tract2cca %>%
  left_join(df_tract, by = "geoid_tract") %>%
  mutate(hu_tot = hu_tot * hu_pct,
         hu_vac = hu_vac * hu_pct) %>%
  group_by(geoid_tract) %>%
  summarize_at(vars(hu_tot, hu_vac), sum) %>%
  mutate(vac_rate = hu_vac / hu_tot)

df_tract
```

# Join to cca_sf for mapping
```{r}
library(ggplot2)
tract_sf %>%
  left_join(df_tract, by = "geoid_tract") %>%
  ggplot() +
    geom_sf(aes(fill = vac_rate), lwd = 0.1) +
    scale_fill_viridis_c(direction = -1) +
    theme_void()
``

